from __future__ import annotations
import math as math
import sys as sys
__all__ = ['Infinity', 'math', 'sys']
class Infinity:
    """
    
        Class representing infinity and minus infinity
        
    """
    def __add__(self, other):
        ...
    def __div__(self, other):
        ...
    def __eq__(self, other):
        ...
    def __ge__(self, other):
        ...
    def __gt__(self, other):
        ...
    def __hash__(self):
        ...
    def __init__(self, negated = False):
        ...
    def __le__(self, other):
        ...
    def __lt__(self, other):
        ...
    def __mul__(self, other):
        ...
    def __neg__(self):
        ...
    def __radd__(self, other):
        ...
    def __rdiv__(self, other):
        ...
    def __repr__(self):
        ...
    def __rmul__(self, other):
        ...
    def __rsub__(self, other):
        ...
    def __str__(self):
        ...
    def __sub__(self, other):
        ...
