"""
pycarl core untyped functions
"""
from __future__ import annotations
import typing
__all__ = ['BoundType', 'Interval', 'Monomial', 'NoPicklingSupport', 'Variable', 'VariableType', 'abs', 'ceil', 'clear_monomial_pool', 'clear_variable_pool', 'create_monomial', 'div', 'floor', 'isInteger', 'pow', 'quotient', 'variable_with_name']
class BoundType:
    """
    Members:
    
      STRICT
    
      WEAK
    
      INFTY
    """
    INFTY: typing.ClassVar[BoundType]  # value = <BoundType.INFTY: 2>
    STRICT: typing.ClassVar[BoundType]  # value = <BoundType.STRICT: 0>
    WEAK: typing.ClassVar[BoundType]  # value = <BoundType.WEAK: 1>
    __members__: typing.ClassVar[dict[str, BoundType]]  # value = {'STRICT': <BoundType.STRICT: 0>, 'WEAK': <BoundType.WEAK: 1>, 'INFTY': <BoundType.INFTY: 2>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class Interval:
    __hash__: typing.ClassVar[None] = None
    @staticmethod
    def emptyInterval() -> Interval:
        ...
    @staticmethod
    def unboundedInterval() -> Interval:
        ...
    @staticmethod
    def zeroInterval() -> Interval:
        ...
    @typing.overload
    def __add__(self, arg0: Interval) -> Interval:
        ...
    @typing.overload
    def __add__(self, arg0: float) -> Interval:
        ...
    def __eq__(self, arg0: Interval) -> bool:
        ...
    @typing.overload
    def __ge__(self, arg0: float) -> bool:
        ...
    @typing.overload
    def __ge__(self, arg0: Interval) -> bool:
        ...
    @typing.overload
    def __ge__(self, arg0: float) -> bool:
        ...
    def __getstate__(self) -> tuple[str]:
        ...
    @typing.overload
    def __gt__(self, arg0: float) -> bool:
        ...
    @typing.overload
    def __gt__(self, arg0: Interval) -> bool:
        ...
    @typing.overload
    def __gt__(self, arg0: float) -> bool:
        ...
    @typing.overload
    def __iadd__(self, arg0: Interval) -> Interval:
        ...
    @typing.overload
    def __iadd__(self, arg0: float) -> Interval:
        ...
    @typing.overload
    def __imul__(self, arg0: Interval) -> Interval:
        ...
    @typing.overload
    def __imul__(self, arg0: float) -> Interval:
        ...
    @typing.overload
    def __init__(self, arg0: float) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: float, arg1: float) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: float, arg1: BoundType, arg2: float, arg3: BoundType) -> None:
        ...
    @typing.overload
    def __isub__(self, arg0: Interval) -> Interval:
        ...
    @typing.overload
    def __isub__(self, arg0: float) -> Interval:
        ...
    def __itruediv__(self, arg0: float) -> Interval:
        ...
    @typing.overload
    def __le__(self, arg0: Interval) -> bool:
        ...
    @typing.overload
    def __le__(self, arg0: float) -> bool:
        ...
    @typing.overload
    def __le__(self, arg0: float) -> bool:
        ...
    @typing.overload
    def __lt__(self, arg0: Interval) -> bool:
        ...
    @typing.overload
    def __lt__(self, arg0: float) -> bool:
        ...
    @typing.overload
    def __lt__(self, arg0: float) -> bool:
        ...
    @typing.overload
    def __mul__(self, arg0: Interval) -> Interval:
        ...
    @typing.overload
    def __mul__(self, arg0: float) -> Interval:
        ...
    def __ne__(self, arg0: Interval) -> bool:
        ...
    def __neg__(self) -> Interval:
        ...
    def __pow__(self, arg0: int) -> Interval:
        ...
    def __radd__(self, arg0: float) -> Interval:
        ...
    def __repr__(self) -> str:
        ...
    def __rmul__(self, arg0: float) -> Interval:
        ...
    def __rsub__(self, arg0: float) -> Interval:
        ...
    def __setstate__(self, arg0: tuple[str]) -> None:
        ...
    def __str__(self) -> str:
        ...
    @typing.overload
    def __sub__(self, arg0: Interval) -> Interval:
        ...
    @typing.overload
    def __sub__(self, arg0: float) -> Interval:
        ...
    def __truediv__(self, arg0: float) -> Interval:
        ...
    def abs(self) -> Interval:
        ...
    def center(self) -> float:
        ...
    def complement(self, arg0: Interval, arg1: Interval) -> bool:
        ...
    @typing.overload
    def contains(self, arg0: float) -> bool:
        ...
    @typing.overload
    def contains(self, arg0: Interval) -> bool:
        ...
    def diameter(self) -> float:
        ...
    def difference(self, arg0: Interval, arg1: Interval, arg2: Interval) -> bool:
        ...
    def div(self, arg0: Interval) -> Interval:
        ...
    def integralPart(self) -> Interval:
        ...
    def intersect(self, arg0: Interval) -> Interval:
        ...
    def intersectsWith(self, arg0: Interval) -> bool:
        ...
    def inverse(self) -> Interval:
        ...
    def isClosedInterval(self) -> bool:
        ...
    def isEmpty(self) -> bool:
        ...
    def isHalfBounded(self) -> bool:
        ...
    def isInfinite(self) -> bool:
        ...
    def isNegative(self) -> bool:
        ...
    def isOne(self) -> bool:
        ...
    def isOpenInterval(self) -> bool:
        ...
    def isPointInterval(self) -> bool:
        ...
    def isPositive(self) -> bool:
        ...
    def isProperSubset(self, arg0: Interval) -> bool:
        ...
    def isSemiNegative(self) -> bool:
        ...
    def isSemiPositive(self) -> bool:
        ...
    def isSubset(self, arg0: Interval) -> bool:
        ...
    def isUnbounded(self) -> bool:
        ...
    def isZero(self) -> bool:
        ...
    def lower(self) -> float:
        ...
    def meets(self, arg0: float) -> bool:
        ...
    def sample(self, arg0: bool) -> float:
        ...
    def setLower(self, arg0: float) -> None:
        ...
    def setUpper(self, arg0: float) -> None:
        ...
    def symmetricDifference(self, arg0: Interval, arg1: Interval, arg2: Interval) -> bool:
        ...
    def unite(self, arg0: Interval, arg1: Interval, arg2: Interval) -> bool:
        ...
    def upper(self) -> float:
        ...
class Monomial:
    def __getitem__(self, arg0: int) -> tuple[Variable, int]:
        ...
    def __getstate__(self) -> tuple[str]:
        ...
    def __hash__(self) -> int:
        ...
    def __iter__(self) -> typing.Iterator:
        ...
    def __len__(self) -> int:
        ...
    @typing.overload
    def __mul__(self, arg0: Monomial) -> Monomial:
        ...
    @typing.overload
    def __mul__(self, arg0: Variable) -> Monomial:
        ...
    @typing.overload
    def __mul__(self: Variable, arg0: Monomial) -> Monomial:
        ...
    def __pos__(self) -> Monomial:
        ...
    def __pow__(self, arg0: int) -> Monomial:
        ...
    def __setstate__(self, arg0: tuple[str]) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def exponents(self) -> list[tuple[Variable, int]]:
        ...
    @property
    def tdeg(self) -> int:
        ...
class NoPicklingSupport(Exception):
    pass
class Variable:
    def __eq__(self, arg0: Variable) -> bool:
        ...
    def __ge__(self, arg0: Variable) -> bool:
        ...
    def __getstate__(self) -> tuple[str, str]:
        ...
    def __gt__(self, arg0: Variable) -> bool:
        ...
    def __hash__(self) -> int:
        ...
    @typing.overload
    def __init__(self, other: Variable) -> None:
        ...
    @typing.overload
    def __init__(self, name: str, type: VariableType = ...) -> None:
        ...
    @typing.overload
    def __init__(self, type: VariableType = ...) -> None:
        ...
    def __le__(self, arg0: Variable) -> bool:
        ...
    def __lt__(self, arg0: Variable) -> bool:
        ...
    def __mul__(self, arg0: Variable) -> ...:
        ...
    def __ne__(self, arg0: Variable) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, arg0: tuple[str, str]) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def id(self) -> int:
        ...
    @property
    def is_no_variable(self) -> bool:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def rank(self) -> int:
        ...
    @property
    def type(self) -> VariableType:
        ...
class VariableType:
    """
    Members:
    
      BOOL
    
      INT
    
      REAL
    """
    BOOL: typing.ClassVar[VariableType]  # value = <VariableType.BOOL: 0>
    INT: typing.ClassVar[VariableType]  # value = <VariableType.INT: 2>
    REAL: typing.ClassVar[VariableType]  # value = <VariableType.REAL: 1>
    __members__: typing.ClassVar[dict[str, VariableType]]  # value = {'BOOL': <VariableType.BOOL: 0>, 'INT': <VariableType.INT: 2>, 'REAL': <VariableType.REAL: 1>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
def abs(arg0: Interval) -> Interval:
    ...
def ceil(arg0: Interval) -> Interval:
    ...
def clear_monomial_pool() -> None:
    """
    Clear monomial pool and remove all monomials
    """
def clear_variable_pool() -> None:
    """
    Clear variable pool and remove all variables
    """
def create_monomial(variable: Variable, exponent: int) -> Monomial:
    """
    Create monomial
    """
def div(arg0: Interval, arg1: Interval) -> Interval:
    ...
def floor(arg0: Interval) -> Interval:
    ...
def isInteger(arg0: Interval) -> bool:
    ...
def pow(arg0: Interval, arg1: int) -> Interval:
    ...
def quotient(arg0: Interval, arg1: Interval) -> Interval:
    ...
def variable_with_name(arg0: str) -> Variable:
    """
    Get a variable from the pool with the given name.
    """
