from __future__ import annotations
from stormpy.pycarl import cln
import stormpy.pycarl.pycarl_core
import typing
from . import _config
__all__ = ['Factorization', 'FactorizedPolynomial', 'FactorizedRationalFunction', 'Integer', 'Interval', 'Polynomial', 'Rational', 'RationalFunction', 'Term', 'abs', 'ceil', 'cln', 'create_factorized_polynomial', 'denominator', 'div', 'expand', 'factorization_cache', 'floor', 'isInteger', 'numerator', 'pow', 'quotient']
class Factorization:
    """
    Factorization
    """
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: Factorization) -> bool:
        ...
    def __getstate__(self) -> tuple[str]:
        ...
    def __iter__(self) -> typing.Iterator:
        ...
    def __len__(self) -> int:
        ...
    def __setstate__(self, arg0: tuple[str]) -> None:
        ...
    def __str__(self) -> str:
        ...
class FactorizedPolynomial:
    """
    Represent a polynomial with its factorization
    """
    coefficient: Rational
    def __add__(self, arg0: FactorizedPolynomial) -> FactorizedPolynomial:
        ...
    @typing.overload
    def __eq__(self, arg0: FactorizedPolynomial) -> bool:
        ...
    @typing.overload
    def __eq__(self, arg0: Rational) -> bool:
        ...
    def __getstate__(self) -> tuple[str]:
        ...
    def __hash__(self) -> int:
        ...
    @typing.overload
    def __init__(self, number: Rational) -> None:
        """
        Constructor
        """
    @typing.overload
    def __init__(self, polynomial: Polynomial, cache: _FactorizationCache) -> None:
        """
        Constructor
        """
    def __mul__(self, arg0: FactorizedPolynomial) -> FactorizedPolynomial:
        ...
    @typing.overload
    def __ne__(self, arg0: FactorizedPolynomial) -> bool:
        ...
    @typing.overload
    def __ne__(self, arg0: Rational) -> bool:
        ...
    def __pow__(self, exponent: int) -> FactorizedPolynomial:
        """
        Raise polynomial to the power
        """
    def __setstate__(self, arg0: tuple[str]) -> None:
        ...
    def __str__(self) -> str:
        ...
    def __sub__(self, arg0: FactorizedPolynomial) -> FactorizedPolynomial:
        ...
    def cache(self) -> _FactorizationCache:
        ...
    def constant_part(self) -> Rational:
        ...
    def derive(self, variable: stormpy.pycarl.pycarl_core.Variable) -> FactorizedPolynomial:
        """
        Compute the derivative
        """
    def evaluate(self, arg0: dict[stormpy.pycarl.pycarl_core.Variable, Rational]) -> Rational:
        ...
    def factorization(self) -> Factorization:
        """
        Get factorization
        """
    def gather_variables(self) -> set[stormpy.pycarl.pycarl_core.Variable]:
        ...
    def is_constant(self) -> bool:
        ...
    def is_one(self) -> bool:
        ...
    def polynomial(self) -> Polynomial:
        """
        Get underlying polynomial
        """
    def to_smt2(self) -> str:
        ...
class FactorizedRationalFunction:
    """
    Represent a rational function, that is the fraction of two factorized polynomials 
    """
    @typing.overload
    def __add__(self, arg0: FactorizedRationalFunction) -> FactorizedRationalFunction:
        ...
    @typing.overload
    def __add__(self, arg0: Rational) -> FactorizedRationalFunction:
        ...
    def __eq__(self, arg0: FactorizedRationalFunction) -> bool:
        ...
    def __getstate__(self) -> tuple[str]:
        ...
    def __hash__(self) -> int:
        ...
    @typing.overload
    def __init__(self, arg0: FactorizedPolynomial) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: FactorizedPolynomial, arg1: FactorizedPolynomial) -> None:
        ...
    def __mul__(self, arg0: FactorizedRationalFunction) -> FactorizedRationalFunction:
        ...
    def __ne__(self, arg0: FactorizedRationalFunction) -> bool:
        ...
    def __setstate__(self, arg0: tuple[str]) -> None:
        ...
    def __str__(self) -> str:
        ...
    def __sub__(self, arg0: FactorizedRationalFunction) -> FactorizedRationalFunction:
        ...
    def __truediv__(self, arg0: FactorizedRationalFunction) -> FactorizedRationalFunction:
        ...
    def constant_part(self) -> Rational:
        ...
    def derive(self, variable: stormpy.pycarl.pycarl_core.Variable) -> FactorizedRationalFunction:
        """
        Compute the derivative
        """
    def evaluate(self, arg0: dict[stormpy.pycarl.pycarl_core.Variable, Rational]) -> Rational:
        ...
    def gather_variables(self) -> set[stormpy.pycarl.pycarl_core.Variable]:
        ...
    def is_constant(self) -> bool:
        ...
    def rational_function(self) -> RationalFunction:
        ...
    def to_smt2(self) -> str:
        ...
    @property
    def denominator(self) -> FactorizedPolynomial:
        ...
    @property
    def numerator(self) -> FactorizedPolynomial:
        ...
class Integer:
    """
    Class wrapping cln-integers
    """
    @staticmethod
    @typing.overload
    def __init__(*args, **kwargs) -> None:
        ...
    def __abs__(self) -> Integer:
        ...
    @typing.overload
    def __add__(self, arg0: Integer) -> Integer:
        ...
    @typing.overload
    def __add__(self, arg0: int) -> Integer:
        ...
    @typing.overload
    def __add__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> ...:
        ...
    @typing.overload
    def __add__(self, arg0: stormpy.pycarl.pycarl_core.Monomial) -> ...:
        ...
    @typing.overload
    def __eq__(self, arg0: Integer) -> bool:
        ...
    @typing.overload
    def __eq__(self, arg0: int) -> bool:
        ...
    def __float__(self) -> float:
        ...
    @typing.overload
    def __ge__(self, arg0: Integer) -> bool:
        ...
    @typing.overload
    def __ge__(self, arg0: int) -> bool:
        ...
    def __getstate__(self) -> tuple[str]:
        ...
    @typing.overload
    def __gt__(self, arg0: Integer) -> bool:
        ...
    @typing.overload
    def __gt__(self, arg0: int) -> bool:
        ...
    def __hash__(self) -> int:
        ...
    @typing.overload
    def __init__(self, arg0: int) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: str) -> None:
        ...
    @typing.overload
    def __le__(self, arg0: Integer) -> bool:
        ...
    @typing.overload
    def __le__(self, arg0: int) -> bool:
        ...
    @typing.overload
    def __lt__(self, arg0: Integer) -> bool:
        ...
    @typing.overload
    def __lt__(self, arg0: int) -> bool:
        ...
    @typing.overload
    def __mul__(self, arg0: Integer) -> Integer:
        ...
    @typing.overload
    def __mul__(self, arg0: int) -> Integer:
        ...
    @typing.overload
    def __mul__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> ...:
        ...
    @typing.overload
    def __mul__(self, arg0: stormpy.pycarl.pycarl_core.Monomial) -> ...:
        ...
    @typing.overload
    def __ne__(self, arg0: Integer) -> bool:
        ...
    @typing.overload
    def __ne__(self, arg0: int) -> bool:
        ...
    def __neg__(self) -> Integer:
        ...
    def __pos__(self) -> Integer:
        ...
    def __pow__(self, arg0: int) -> Integer:
        ...
    @typing.overload
    def __radd__(self, arg0: int) -> Integer:
        ...
    @typing.overload
    def __radd__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> ...:
        ...
    @typing.overload
    def __radd__(self, arg0: stormpy.pycarl.pycarl_core.Monomial) -> ...:
        ...
    def __repr__(self) -> str:
        ...
    @typing.overload
    def __rmul__(self, arg0: int) -> Integer:
        ...
    @typing.overload
    def __rmul__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> ...:
        ...
    @typing.overload
    def __rmul__(self, arg0: stormpy.pycarl.pycarl_core.Monomial) -> ...:
        ...
    def __rsub__(self, arg0: int) -> Integer:
        ...
    def __setstate__(self, arg0: tuple[str]) -> None:
        ...
    def __str__(self) -> str:
        ...
    @typing.overload
    def __sub__(self, arg0: Integer) -> Integer:
        ...
    @typing.overload
    def __sub__(self, arg0: int) -> Integer:
        ...
    @typing.overload
    def __sub__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> ...:
        ...
    @typing.overload
    def __sub__(self, arg0: stormpy.pycarl.pycarl_core.Monomial) -> ...:
        ...
    def __truediv__(self, arg0: Integer) -> ...:
        ...
class Interval:
    __hash__: typing.ClassVar[None] = None
    @staticmethod
    def emptyInterval() -> Interval:
        ...
    @staticmethod
    def unboundedInterval() -> Interval:
        ...
    @staticmethod
    def zeroInterval() -> Interval:
        ...
    @typing.overload
    def __add__(self, arg0: Interval) -> Interval:
        ...
    @typing.overload
    def __add__(self, arg0: Rational) -> Interval:
        ...
    def __eq__(self, arg0: Interval) -> bool:
        ...
    @typing.overload
    def __ge__(self, arg0: Rational) -> bool:
        ...
    @typing.overload
    def __ge__(self, arg0: Interval) -> bool:
        ...
    @typing.overload
    def __ge__(self, arg0: Rational) -> bool:
        ...
    def __getstate__(self) -> tuple[str]:
        ...
    @typing.overload
    def __gt__(self, arg0: Rational) -> bool:
        ...
    @typing.overload
    def __gt__(self, arg0: Interval) -> bool:
        ...
    @typing.overload
    def __gt__(self, arg0: Rational) -> bool:
        ...
    @typing.overload
    def __iadd__(self, arg0: Interval) -> Interval:
        ...
    @typing.overload
    def __iadd__(self, arg0: Rational) -> Interval:
        ...
    @typing.overload
    def __imul__(self, arg0: Interval) -> Interval:
        ...
    @typing.overload
    def __imul__(self, arg0: Rational) -> Interval:
        ...
    @typing.overload
    def __init__(self, arg0: Rational) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: Rational, arg1: Rational) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: Rational, arg1: stormpy.pycarl.pycarl_core.BoundType, arg2: Rational, arg3: stormpy.pycarl.pycarl_core.BoundType) -> None:
        ...
    @typing.overload
    def __isub__(self, arg0: Interval) -> Interval:
        ...
    @typing.overload
    def __isub__(self, arg0: Rational) -> Interval:
        ...
    def __itruediv__(self, arg0: Rational) -> Interval:
        ...
    @typing.overload
    def __le__(self, arg0: Interval) -> bool:
        ...
    @typing.overload
    def __le__(self, arg0: Rational) -> bool:
        ...
    @typing.overload
    def __le__(self, arg0: Rational) -> bool:
        ...
    @typing.overload
    def __lt__(self, arg0: Interval) -> bool:
        ...
    @typing.overload
    def __lt__(self, arg0: Rational) -> bool:
        ...
    @typing.overload
    def __lt__(self, arg0: Rational) -> bool:
        ...
    @typing.overload
    def __mul__(self, arg0: Interval) -> Interval:
        ...
    @typing.overload
    def __mul__(self, arg0: Rational) -> Interval:
        ...
    def __ne__(self, arg0: Interval) -> bool:
        ...
    def __neg__(self) -> Interval:
        ...
    def __pow__(self, arg0: int) -> Interval:
        ...
    def __radd__(self, arg0: Rational) -> Interval:
        ...
    def __repr__(self) -> str:
        ...
    def __rmul__(self, arg0: Rational) -> Interval:
        ...
    def __rsub__(self, arg0: Rational) -> Interval:
        ...
    def __setstate__(self, arg0: tuple[str]) -> None:
        ...
    def __str__(self) -> str:
        ...
    @typing.overload
    def __sub__(self, arg0: Interval) -> Interval:
        ...
    @typing.overload
    def __sub__(self, arg0: Rational) -> Interval:
        ...
    def __truediv__(self, arg0: Rational) -> Interval:
        ...
    def abs(self) -> Interval:
        ...
    def center(self) -> Rational:
        ...
    def complement(self, arg0: Interval, arg1: Interval) -> bool:
        ...
    @typing.overload
    def contains(self, arg0: Rational) -> bool:
        ...
    @typing.overload
    def contains(self, arg0: Interval) -> bool:
        ...
    def diameter(self) -> Rational:
        ...
    def difference(self, arg0: Interval, arg1: Interval, arg2: Interval) -> bool:
        ...
    def div(self, arg0: Interval) -> Interval:
        ...
    def integralPart(self) -> Interval:
        ...
    def intersect(self, arg0: Interval) -> Interval:
        ...
    def intersectsWith(self, arg0: Interval) -> bool:
        ...
    def inverse(self) -> Interval:
        ...
    def isClosedInterval(self) -> bool:
        ...
    def isEmpty(self) -> bool:
        ...
    def isHalfBounded(self) -> bool:
        ...
    def isInfinite(self) -> bool:
        ...
    def isNegative(self) -> bool:
        ...
    def isOne(self) -> bool:
        ...
    def isOpenInterval(self) -> bool:
        ...
    def isPointInterval(self) -> bool:
        ...
    def isPositive(self) -> bool:
        ...
    def isProperSubset(self, arg0: Interval) -> bool:
        ...
    def isSemiNegative(self) -> bool:
        ...
    def isSemiPositive(self) -> bool:
        ...
    def isSubset(self, arg0: Interval) -> bool:
        ...
    def isUnbounded(self) -> bool:
        ...
    def isZero(self) -> bool:
        ...
    def lower(self) -> Rational:
        ...
    def meets(self, arg0: Rational) -> bool:
        ...
    def sample(self, arg0: bool) -> Rational:
        ...
    def setLower(self, arg0: Rational) -> None:
        ...
    def setUpper(self, arg0: Rational) -> None:
        ...
    def symmetricDifference(self, arg0: Interval, arg1: Interval, arg2: Interval) -> bool:
        ...
    def unite(self, arg0: Interval, arg1: Interval, arg2: Interval) -> bool:
        ...
    def upper(self) -> Rational:
        ...
class Polynomial:
    """
    Represent a multivariate polynomial
    """
    @staticmethod
    @typing.overload
    def __add__(*args, **kwargs) -> ...:
        ...
    @staticmethod
    @typing.overload
    def __truediv__(*args, **kwargs) -> ...:
        ...
    @typing.overload
    def __add__(self, arg0: Integer) -> Polynomial:
        ...
    @typing.overload
    def __add__(self, arg0: Rational) -> Polynomial:
        ...
    @typing.overload
    def __add__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> Polynomial:
        ...
    @typing.overload
    def __add__(self, arg0: stormpy.pycarl.pycarl_core.Monomial) -> Polynomial:
        ...
    @typing.overload
    def __add__(self, arg0: Term) -> Polynomial:
        ...
    @typing.overload
    def __add__(self, arg0: Polynomial) -> Polynomial:
        ...
    @typing.overload
    def __eq__(self, arg0: Polynomial) -> bool:
        ...
    @typing.overload
    def __eq__(self, arg0: Rational) -> bool:
        ...
    @typing.overload
    def __eq__(self, arg0: Integer) -> bool:
        ...
    def __getitem__(self, arg0: int) -> Term:
        ...
    def __getstate__(self) -> tuple[str]:
        ...
    def __hash__(self) -> int:
        ...
    @typing.overload
    def __init__(self, arg0: Term) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: stormpy.pycarl.pycarl_core.Monomial) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: Rational) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: list[Term]) -> None:
        ...
    def __iter__(self) -> typing.Iterator:
        ...
    def __len__(self) -> int:
        ...
    @typing.overload
    def __mul__(self, arg0: Integer) -> Polynomial:
        ...
    @typing.overload
    def __mul__(self, arg0: Rational) -> Polynomial:
        ...
    @typing.overload
    def __mul__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> Polynomial:
        ...
    @typing.overload
    def __mul__(self, arg0: stormpy.pycarl.pycarl_core.Monomial) -> Polynomial:
        ...
    @typing.overload
    def __mul__(self, arg0: Term) -> Polynomial:
        ...
    @typing.overload
    def __mul__(self, arg0: Polynomial) -> Polynomial:
        ...
    @typing.overload
    def __ne__(self, arg0: Polynomial) -> bool:
        ...
    @typing.overload
    def __ne__(self, arg0: Rational) -> bool:
        ...
    @typing.overload
    def __ne__(self, arg0: Integer) -> bool:
        ...
    def __neg__(self) -> Polynomial:
        ...
    def __pos__(self) -> Polynomial:
        ...
    def __pow__(self, arg0: int) -> Polynomial:
        ...
    def __radd__(self, arg0: stormpy.pycarl.pycarl_core.Monomial) -> Polynomial:
        ...
    def __repr__(self) -> str:
        ...
    @typing.overload
    def __rmul__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> Polynomial:
        ...
    @typing.overload
    def __rmul__(self, arg0: stormpy.pycarl.pycarl_core.Monomial) -> Polynomial:
        ...
    @typing.overload
    def __rsub__(self, arg0: stormpy.pycarl.pycarl_core.Monomial) -> Polynomial:
        ...
    @typing.overload
    def __rsub__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> Polynomial:
        ...
    def __setstate__(self, arg0: tuple[str]) -> None:
        ...
    def __str__(self) -> str:
        ...
    @typing.overload
    def __sub__(self, arg0: Integer) -> Polynomial:
        ...
    @typing.overload
    def __sub__(self, arg0: Rational) -> Polynomial:
        ...
    @typing.overload
    def __sub__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> Polynomial:
        ...
    @typing.overload
    def __sub__(self, arg0: stormpy.pycarl.pycarl_core.Monomial) -> Polynomial:
        ...
    @typing.overload
    def __sub__(self, arg0: Term) -> Polynomial:
        ...
    @typing.overload
    def __sub__(self, arg0: Polynomial) -> Polynomial:
        ...
    @typing.overload
    def __truediv__(self, arg0: Polynomial) -> ...:
        ...
    @typing.overload
    def __truediv__(self, arg0: Term) -> ...:
        ...
    @typing.overload
    def __truediv__(self, arg0: stormpy.pycarl.pycarl_core.Monomial) -> ...:
        ...
    @typing.overload
    def __truediv__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> ...:
        ...
    @typing.overload
    def __truediv__(self, arg0: Rational) -> Polynomial:
        ...
    @typing.overload
    def __truediv__(self, arg0: Integer) -> Polynomial:
        ...
    def constant_part(self) -> Rational:
        ...
    def degree(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> int:
        ...
    def derive(self, variable: stormpy.pycarl.pycarl_core.Variable) -> Polynomial:
        """
        Compute the derivative
        """
    def evaluate(self, arg0: dict[stormpy.pycarl.pycarl_core.Variable, Rational]) -> Rational:
        ...
    def gather_variables(self) -> set[stormpy.pycarl.pycarl_core.Variable]:
        ...
    def is_constant(self) -> bool:
        ...
    def substitute(self, arg0: dict[stormpy.pycarl.pycarl_core.Variable, Polynomial]) -> Polynomial:
        ...
    def to_smt2(self) -> str:
        ...
    @property
    def nr_terms(self) -> int:
        ...
    @property
    def total_degree(self) -> int:
        ...
class Rational:
    """
    Class wrapping cln-rational numbers
    """
    @staticmethod
    @typing.overload
    def __add__(*args, **kwargs) -> ...:
        ...
    @staticmethod
    @typing.overload
    def __init__(*args, **kwargs) -> None:
        ...
    @staticmethod
    @typing.overload
    def __truediv__(*args, **kwargs) -> ...:
        ...
    def __abs__(self) -> Rational:
        ...
    @typing.overload
    def __add__(self, arg0: Rational) -> Rational:
        ...
    @typing.overload
    def __add__(self, arg0: int) -> Rational:
        ...
    @typing.overload
    def __add__(self, arg0: ..., carl: ..., carl: ...) -> ...:
        ...
    @typing.overload
    def __eq__(self, arg0: Rational) -> bool:
        ...
    @typing.overload
    def __eq__(self, arg0: Integer) -> bool:
        ...
    @typing.overload
    def __eq__(self, arg0: ..., carl: ..., carl: ...) -> bool:
        ...
    @typing.overload
    def __eq__(self, arg0: int) -> bool:
        ...
    def __float__(self) -> float:
        ...
    @typing.overload
    def __ge__(self, arg0: Rational) -> bool:
        ...
    @typing.overload
    def __ge__(self, arg0: Integer) -> bool:
        ...
    @typing.overload
    def __ge__(self, arg0: int) -> bool:
        ...
    def __getstate__(self) -> tuple[str, str]:
        ...
    @typing.overload
    def __gt__(self, arg0: Rational) -> bool:
        ...
    @typing.overload
    def __gt__(self, arg0: Integer) -> bool:
        ...
    @typing.overload
    def __gt__(self, arg0: int) -> bool:
        ...
    def __hash__(self) -> int:
        ...
    @typing.overload
    def __init__(self, arg0: float) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: int) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: Integer, arg1: Integer) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: str) -> None:
        ...
    @typing.overload
    def __le__(self, arg0: Rational) -> bool:
        ...
    @typing.overload
    def __le__(self, arg0: Integer) -> bool:
        ...
    @typing.overload
    def __le__(self, arg0: int) -> bool:
        ...
    @typing.overload
    def __lt__(self, arg0: Rational) -> bool:
        ...
    @typing.overload
    def __lt__(self, arg0: Integer) -> bool:
        ...
    @typing.overload
    def __lt__(self, arg0: int) -> bool:
        ...
    @typing.overload
    def __mul__(self, arg0: Rational) -> Rational:
        ...
    @typing.overload
    def __mul__(self, arg0: int) -> Rational:
        ...
    @typing.overload
    def __mul__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> ...:
        ...
    @typing.overload
    def __ne__(self, arg0: Rational) -> bool:
        ...
    @typing.overload
    def __ne__(self, arg0: Integer) -> bool:
        ...
    @typing.overload
    def __ne__(self, arg0: ..., carl: ..., carl: ...) -> bool:
        ...
    @typing.overload
    def __ne__(self, arg0: int) -> bool:
        ...
    def __neg__(self) -> Rational:
        ...
    def __pos__(self) -> Rational:
        ...
    def __pow__(self, arg0: int) -> Rational:
        ...
    @typing.overload
    def __radd__(self, arg0: int) -> Rational:
        ...
    @typing.overload
    def __radd__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> ...:
        ...
    def __repr__(self) -> str:
        ...
    @typing.overload
    def __rmul__(self, arg0: int) -> Rational:
        ...
    @typing.overload
    def __rmul__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> ...:
        ...
    @typing.overload
    def __rsub__(self, arg0: int) -> Rational:
        ...
    @typing.overload
    def __rsub__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> ...:
        ...
    @typing.overload
    def __rtruediv__(self, arg0: int) -> Rational:
        ...
    @typing.overload
    def __rtruediv__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> ...:
        ...
    def __setstate__(self, arg0: tuple[str, str]) -> None:
        ...
    def __str__(self) -> str:
        ...
    @typing.overload
    def __sub__(self, arg0: Rational) -> Rational:
        ...
    @typing.overload
    def __sub__(self, arg0: int) -> Rational:
        ...
    @typing.overload
    def __sub__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> ...:
        ...
    @typing.overload
    def __truediv__(self, arg0: Rational) -> Rational:
        ...
    @typing.overload
    def __truediv__(self, arg0: int) -> Rational:
        ...
    @typing.overload
    def __truediv__(self, arg0: ..., carl: ..., carl: ...) -> ...:
        ...
    @typing.overload
    def __truediv__(self, arg0: ...) -> ...:
        ...
    @typing.overload
    def __truediv__(self, arg0: stormpy.pycarl.pycarl_core.Monomial) -> ...:
        ...
    @typing.overload
    def __truediv__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> ...:
        ...
    def is_minus_one(self) -> bool:
        ...
    def is_one(self) -> bool:
        ...
    @property
    def denominator(self) -> Integer:
        ...
    @property
    def nominator(self) -> Integer:
        ...
    @property
    def numerator(self) -> Integer:
        ...
class RationalFunction:
    """
    Represent a rational function, that is the fraction of two multivariate polynomials 
    """
    @typing.overload
    def __add__(self, arg0: Polynomial) -> RationalFunction:
        ...
    @typing.overload
    def __add__(self, arg0: Term) -> RationalFunction:
        ...
    @typing.overload
    def __add__(self, arg0: stormpy.pycarl.pycarl_core.Monomial) -> RationalFunction:
        ...
    @typing.overload
    def __add__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> RationalFunction:
        ...
    @typing.overload
    def __add__(self, arg0: Rational) -> RationalFunction:
        ...
    @typing.overload
    def __add__(self, arg0: RationalFunction) -> RationalFunction:
        ...
    @typing.overload
    def __eq__(self, arg0: RationalFunction) -> bool:
        ...
    @typing.overload
    def __eq__(self, arg0: Polynomial) -> bool:
        ...
    def __getstate__(self) -> tuple[str]:
        ...
    def __hash__(self) -> int:
        ...
    @typing.overload
    def __init__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: Polynomial) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: Polynomial, arg1: Polynomial) -> None:
        ...
    @typing.overload
    def __mul__(self, arg0: Polynomial) -> RationalFunction:
        ...
    @typing.overload
    def __mul__(self, arg0: Term) -> RationalFunction:
        ...
    @typing.overload
    def __mul__(self, arg0: stormpy.pycarl.pycarl_core.Monomial) -> RationalFunction:
        ...
    @typing.overload
    def __mul__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> RationalFunction:
        ...
    @typing.overload
    def __mul__(self, arg0: Rational) -> RationalFunction:
        ...
    @typing.overload
    def __mul__(self, arg0: RationalFunction) -> RationalFunction:
        ...
    @typing.overload
    def __ne__(self, arg0: RationalFunction) -> bool:
        ...
    @typing.overload
    def __ne__(self, arg0: Polynomial) -> bool:
        ...
    def __neg__(self) -> RationalFunction:
        ...
    def __pos__(self) -> RationalFunction:
        ...
    def __pow__(self, arg0: int) -> RationalFunction:
        ...
    @typing.overload
    def __radd__(self, arg0: Polynomial) -> RationalFunction:
        ...
    @typing.overload
    def __radd__(self, arg0: Term) -> RationalFunction:
        ...
    @typing.overload
    def __radd__(self, arg0: stormpy.pycarl.pycarl_core.Monomial) -> RationalFunction:
        ...
    @typing.overload
    def __radd__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> RationalFunction:
        ...
    @typing.overload
    def __radd__(self, arg0: Rational) -> RationalFunction:
        ...
    def __rmul__(self, arg0: Polynomial) -> RationalFunction:
        ...
    def __setstate__(self, arg0: tuple[str]) -> None:
        ...
    def __str__(self) -> str:
        ...
    @typing.overload
    def __sub__(self, arg0: Polynomial) -> RationalFunction:
        ...
    @typing.overload
    def __sub__(self, arg0: Term) -> RationalFunction:
        ...
    @typing.overload
    def __sub__(self, arg0: stormpy.pycarl.pycarl_core.Monomial) -> RationalFunction:
        ...
    @typing.overload
    def __sub__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> RationalFunction:
        ...
    @typing.overload
    def __sub__(self, arg0: Rational) -> RationalFunction:
        ...
    @typing.overload
    def __sub__(self, arg0: RationalFunction) -> RationalFunction:
        ...
    @typing.overload
    def __truediv__(self, arg0: Rational) -> RationalFunction:
        ...
    @typing.overload
    def __truediv__(self, arg0: Polynomial) -> RationalFunction:
        ...
    @typing.overload
    def __truediv__(self, arg0: Term) -> RationalFunction:
        ...
    @typing.overload
    def __truediv__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> RationalFunction:
        ...
    @typing.overload
    def __truediv__(self, arg0: Rational) -> RationalFunction:
        ...
    @typing.overload
    def __truediv__(self, arg0: RationalFunction) -> RationalFunction:
        ...
    def constant_part(self) -> Rational:
        ...
    def derive(self, variable: stormpy.pycarl.pycarl_core.Variable) -> RationalFunction:
        """
        Compute the derivative
        """
    def evaluate(self, arg0: dict[stormpy.pycarl.pycarl_core.Variable, Rational]) -> Rational:
        ...
    def gather_variables(self) -> set[stormpy.pycarl.pycarl_core.Variable]:
        ...
    def is_constant(self) -> bool:
        ...
    def to_smt2(self) -> str:
        ...
    @property
    def denominator(self) -> Polynomial:
        ...
    @property
    def nominator(self) -> Polynomial:
        ...
    @property
    def numerator(self) -> Polynomial:
        ...
class Term:
    @staticmethod
    @typing.overload
    def __truediv__(*args, **kwargs) -> ...:
        ...
    @typing.overload
    def __add__(self, arg0: ..., carl: ..., carl: ...) -> ...:
        ...
    @typing.overload
    def __add__(self, arg0: Term) -> ...:
        ...
    @typing.overload
    def __add__(self, arg0: stormpy.pycarl.pycarl_core.Monomial) -> ...:
        ...
    @typing.overload
    def __add__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> ...:
        ...
    @typing.overload
    def __add__(self, arg0: Rational) -> ...:
        ...
    def __eq__(self, arg0: Term) -> bool:
        ...
    def __getstate__(self) -> tuple[str]:
        ...
    def __hash__(self) -> int:
        ...
    @typing.overload
    def __init__(self, arg0: Rational, arg1: stormpy.pycarl.pycarl_core.Monomial) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: Rational) -> None:
        ...
    @typing.overload
    def __mul__(self, arg0: ..., carl: ..., carl: ...) -> ...:
        ...
    @typing.overload
    def __mul__(self, arg0: Term) -> Term:
        ...
    @typing.overload
    def __mul__(self, arg0: stormpy.pycarl.pycarl_core.Monomial) -> Term:
        ...
    @typing.overload
    def __mul__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> Term:
        ...
    @typing.overload
    def __mul__(self, arg0: Rational) -> Term:
        ...
    def __ne__(self, arg0: Term) -> bool:
        ...
    def __neg__(self) -> Term:
        ...
    def __pos__(self) -> Term:
        ...
    def __pow__(self, arg0: int) -> Term:
        ...
    def __setstate__(self, arg0: tuple[str]) -> None:
        ...
    def __str__(self) -> str:
        ...
    @typing.overload
    def __sub__(self, arg0: ..., carl: ..., carl: ...) -> ...:
        ...
    @typing.overload
    def __sub__(self, arg0: Term) -> ...:
        ...
    @typing.overload
    def __sub__(self, arg0: stormpy.pycarl.pycarl_core.Monomial) -> ...:
        ...
    @typing.overload
    def __sub__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> ...:
        ...
    @typing.overload
    def __sub__(self, arg0: Rational) -> ...:
        ...
    @typing.overload
    def __truediv__(self, arg0: ..., carl: ..., carl: ...) -> ...:
        ...
    @typing.overload
    def __truediv__(self, arg0: Term) -> ...:
        ...
    @typing.overload
    def __truediv__(self, arg0: stormpy.pycarl.pycarl_core.Monomial) -> ...:
        ...
    @typing.overload
    def __truediv__(self, arg0: stormpy.pycarl.pycarl_core.Variable) -> ...:
        ...
    @typing.overload
    def __truediv__(self, arg0: Rational) -> Term:
        ...
    def is_constant(self) -> bool:
        ...
    def is_one(self) -> bool:
        ...
    @property
    def coeff(self) -> Rational:
        ...
    @property
    def monomial(self) -> stormpy.pycarl.pycarl_core.Monomial:
        ...
    @property
    def tdeg(self) -> int:
        ...
def abs(arg0: Interval) -> Interval:
    ...
def ceil(arg0: Interval) -> Interval:
    ...
def create_factorized_polynomial(polynomial):
    ...
def denominator(x):
    ...
def div(arg0: Interval, arg1: Interval) -> Interval:
    ...
def expand(x):
    ...
def floor(arg0: Interval) -> Interval:
    ...
def isInteger(arg0: Interval) -> bool:
    ...
def numerator(x):
    ...
def pow(arg0: Interval, arg1: int) -> Interval:
    ...
def quotient(arg0: Interval, arg1: Interval) -> Interval:
    ...
factorization_cache: _FactorizationCache  # value = <stormpy.pycarl.cln._FactorizationCache object>
