name: Check code format

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check_python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: psf/black@stable
      with:
        options: "--check --diff --color"
        src: "."
        jupyter: true

  check_cpp:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: DoozyX/clang-format-lint-action@v0.20
      with:
        source: './src'
        clangFormatVersion: 20
        style: file

  check_docs_format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-python@v7
      with:
        python-version: '3.x'
    - run: |
        JUPYTEXT_VERSION=$(sed -n 's/.*"jupytext==\([0-9.]*\)".*/\1/p' pyproject.toml)
        BLACK_VERSION=$(sed -n 's/.*"black\[jupyter\]==\([0-9.]*\)".*/\1/p' pyproject.toml)
        pip install "black[jupyter]==$BLACK_VERSION" "jupytext==$JUPYTEXT_VERSION"
    - run: make check-format-doc
